### PR TITLE
Upgrading kube-prometheus-stack to v52.1.0

### PR DESCRIPTION
**Pull request by manasabsv26**
## ISSUE(S):
[PMK-5930](https://platform9.atlassian.net/browse/PMK-5930)

## SUMMARY:
Upgraded `kube-prometheus-stack` version from v38.0.2 (monitoring version - v0.57.0) to v52.1.0 (monitoring version - v0.68.0)

## TESTING

* Created a helm chart
```
helm package ./charts/kube-prometheus-stack --destination .deploy   
Successfully packaged chart and saved it to: .deploy/kube-prometheus-stack-52.1.0.tgz
```

* Installed helm-chart
```
helm install proms .deploy/kube-prometheus-stack-52.1.0.tgz       
NAME: proms
LAST DEPLOYED: Wed Nov  8 14:35:48 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace pf9-monitoring get pods -l "release=proms"
```

```
manasab@FVFGQ3B0Q05P pf9-kube-prometheus-helm-chart % helm ls
NAME 	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
proms	default  	1       	2023-11-08 14:35:48.951263 +0530 IST	deployed	kube-prometheus-stack-52.1.0	v0.68.0   
```

```
 kubectl get pods -n pf9-monitoring
NAME                                       READY   STATUS    RESTARTS   AGE
alertmanager-pf9-prom-alertmanager-0       2/2     Running   0          106m
monhelper-58679b95df-nsgj5                 1/1     Running   0          106m
pf9-prom-operator-69c9c7f6cf-9sxqn         1/1     Running   0          106m
prometheus-pf9-prom-prometheus-0           2/2     Running   0          106m
proms-grafana-68897c9d9f-mp7f8             3/3     Running   0          106m
proms-kube-state-metrics-9c55664bb-nh97j   1/1     Running   0          106m
proms-prometheus-node-exporter-h9f2z       1/1     Running   0          106m
proms-prometheus-node-exporter-ww26c       1/1     Running   0          106m
```

```
kubectl get svc -n pf9-monitoring
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
alertmanager-operated            ClusterIP   None            <none>        9093/TCP,9094/TCP,9094/UDP   17m
pf9-prom-alertmanager            ClusterIP   10.21.93.170    <none>        9093/TCP,8080/TCP            17m
pf9-prom-operator                ClusterIP   10.21.222.64    <none>        8080/TCP                     17m
pf9-prom-prometheus              ClusterIP   10.21.162.156   <none>        9090/TCP,8080/TCP            17m
pf9-prometheus-stack-mon-svc     ClusterIP   None            <none>        8080/TCP                     17m
prometheus-operated              ClusterIP   None            <none>        9090/TCP                     17m
proms-grafana                    NodePort    10.21.9.174     <none>        80:32432/TCP                 17m
proms-kube-state-metrics         ClusterIP   10.21.46.206    <none>        8080/TCP                     17m
proms-prometheus-node-exporter   ClusterIP   10.21.208.79    <none>        9100/TCP                     17m
```

* Checked Prometheus UI

```
kubectl port-forward  prometheus-pf9-prom-prometheus-0       9090:9090 -n pf9-monitoring
```
image

* Can see that prometheus is scraping from all the expected targets : node exporter, ksm, monhelper, kubelet, apiserver etc

Screenshot 2023-11-08 at 5 50 55 PM

Screenshot 2023-11-08 at 5 50 36 PM

* Checked Grafana UI

image

Screenshot 2023-11-08 at 5 07 02 PM

Some Dashboards:

image

[PMK-5930]: https://platform9.atlassian.net/browse/PMK-5930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by srm6867 — APPROVED** [review]

**Review by psarwate — APPROVED** [review]
/lgtm

**Review by joey00072 — APPROVED** [review]

**Comment by anmolsachan** [comment]
@manasabsv26 Have you tested if the helm upgrade works from the previous version to this? User has already older version running, they should be able to upgrade to this version with helm without uninstall and re-install.

**Comment by manasabsv26** [comment]
@anmolsachan 
When I tested upgrade initially, I saw this error:
```
client.go:687: [debug] Patch DaemonSet "kps-prometheus-node-exporter" in namespace pf9-monitoring
client.go:417: [debug] error updating the resource "kps-prometheus-node-exporter":
	 cannot patch "kps-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "kps-prometheus-node-exporter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kps", "app.kubernetes.io/name":"prometheus-node-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Then in upstream, I found this: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#from-39x-to-40x

where it says to delete prometheus-node-exporter daemonset before upgrading:
```
From 39.x to 40.x
This version also upgrades the Helm charts of kube-state-metrics to 4.18.0 and prometheus-node-exporter to 4.2.0.

Starting from prometheus-node-exporter version 4.0.0, the node exporter chart is using the [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). Therefore you have to delete the daemonset before you upgrade.

kubectl delete daemonset -l app=prometheus-node-exporter
helm upgrade -i kube-prometheus-stack prometheus-community/kube-prometheus-stack
```

So I tried that, and upgrade then worked:

```
helm ls
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
kps 	default  	1       	2023-11-09 00:10:07.984702 +0530 IST	deployed	kube-prometheus-stack-38.0.2	0.57.0     
```

* Deleting daemonset and upgrading
```
kubectl delete daemonset -l app=prometheus-node-exporter -n pf9-monitoring
daemonset.apps "kps-prometheus-node-exporter" deleted
manasab@FVFGQ3B0Q05P pf9-kube-prometheus-helm-chart % helm upgrade --install kps .deploy/kube-prometheus-stack-52.1.0.tgz


upgrade.go:165: [debug] updating status for upgraded release for kps
Release "kps" has been upgraded. Happy Helming!
NAME: kps
LAST DEPLOYED: Thu Nov  9 01:15:01 2023
NAMESPACE: default
STATUS: deployed
REVISION: 4
USER-SUPPLIED 
```

```
helm ls
NAME	NAMESPACE	REVISION	UPDATED                            	STATUS  	CHART                       	APP VERSION
kps 	default  	4       	2023-11-09 01:15:01.44044 +0530 IST	deployed	kube-prometheus-stack-52.1.0	v0.68.0    
```

```
kubectl get pods -n pf9-monitoring
NAME                                     READY   STATUS    RESTARTS   AGE
alertmanager-pf9-prom-alertmanager-0     2/2     Running   0          58m
kps-grafana-fcf95ff7-zm8xc               3/3     Running   0          58m
kps-kube-state-metrics-7d44bd4f8-76866   1/1     Running   0          58m
kps-prometheus-node-exporter-g4kmw       1/1     Running   0          6m12s
kps-prometheus-node-exporter-ncr8m       1/1     Running   0          6m12s
monhelper-d7964b89b-76vdl                1/1     Running   0          71m
pf9-prom-operator-6c7c68549c-hx7kl       1/1     Running   0          58m
prometheus-pf9-prom-prometheus-0         2/2     Running   0          58m
```

prometheus pod events:
```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  60m   default-scheduler  Successfully assigned pf9-monitoring/prometheus-pf9-prom-prometheus-0 to 10.149.107.110
  Normal  Pulled     60m   kubelet            Container image "quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0" already present on machine
  Normal  Created    60m   kubelet            Created container init-config-reloader
  Normal  Started    60m   kubelet            Started container init-config-reloader
  Normal  Pulled     60m   kubelet            Container image "quay.io/prometheus/prometheus:v2.47.1" already present on 
```
I could also see the required targets in prometheus UI.

**Review by nehatomar12 — APPROVED** [review]
/lgtm

**Pull request merged**
